import {env} from 'cloudflare:workers';
import {buildPushPayload,type PushSubscription} from '@block65/webcrypto-web-push';
import {authDatabase,getTeamUser,sameOrigin} from '@/lib/team-auth';
export const dynamic='force-dynamic';
type Stored={endpoint:string;p256dh:string;auth:string};
const reply=(v:unknown,s=200)=>Response.json(v,{status:s,headers:{'Cache-Control':'no-store, private','X-Content-Type-Options':'nosniff'}});
const config=()=>env as unknown as Record<string,string>;
async function table(){await authDatabase().prepare('CREATE TABLE IF NOT EXISTS push_subscriptions (endpoint TEXT PRIMARY KEY, p256dh TEXT NOT NULL, auth TEXT NOT NULL, username TEXT NOT NULL, updated_at INTEGER NOT NULL)').run()}
function valid(v:any):v is PushSubscription{return !!v&&typeof v.endpoint==='string'&&v.endpoint.startsWith('https://')&&v.endpoint.length<2048&&typeof v.keys?.p256dh==='string'&&v.keys.p256dh.length<256&&typeof v.keys?.auth==='string'&&v.keys.auth.length<256}
function equal(a:string,b:string){if(a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0}
export async function GET(req:Request){if(!await getTeamUser(req))return reply({error:'Sign in to manage notifications.'},401);return reply({publicKey:config().VAPID_PUBLIC_KEY||''})}
export async function POST(req:Request){
 const e=config(),cron=req.headers.get('authorization')?.replace(/^Bearer\s+/,'');
 if(cron&&e.NOTIFICATION_CRON_SECRET&&equal(cron,e.NOTIFICATION_CRON_SECRET)){await table();const body=await req.json().catch(()=>({})) as {slot?:string};if(!['listing','status'].includes(body.slot||''))return reply({error:'Unknown notification.'},400);const rows=(await authDatabase().prepare('SELECT endpoint,p256dh,auth FROM push_subscriptions').all<Stored>()).results||[],message=JSON.stringify({title:'LawPal',body:body.slot==='status'?"Review today's case status updates in LawPal.":"Review today's court listing and prepare the scheduled matters.",url:'/'});let sent=0;for(const row of rows){try{const payload=await buildPushPayload({data:message,options:{ttl:3600}},{endpoint:row.endpoint,expirationTime:null,keys:{p256dh:row.p256dh,auth:row.auth}},{subject:e.VAPID_SUBJECT||'mailto:prabhakarlawgroup@gmail.com',publicKey:e.VAPID_PUBLIC_KEY,privateKey:e.VAPID_PRIVATE_KEY});const r=await fetch(row.endpoint,payload);if(r.ok)sent++;else if(r.status===404||r.status===410)await authDatabase().prepare('DELETE FROM push_subscriptions WHERE endpoint=?').bind(row.endpoint).run()}catch{}}return reply({ok:true,sent})}
 const user=await getTeamUser(req);if(!user)return reply({error:'Sign in to manage notifications.'},401);if(!sameOrigin(req))return reply({error:'Request origin is not allowed.'},403);const body=await req.json().catch(()=>({})) as {action?:string;subscription?:PushSubscription};await table();if(!valid(body.subscription))return reply({error:'Invalid notification subscription.'},400);if(body.action==='unsubscribe'){await authDatabase().prepare('DELETE FROM push_subscriptions WHERE endpoint=?').bind(body.subscription.endpoint).run();return reply({ok:true})}if(body.action!=='subscribe')return reply({error:'Unknown action.'},400);await authDatabase().prepare('INSERT INTO push_subscriptions(endpoint,p256dh,auth,username,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(endpoint) DO UPDATE SET p256dh=excluded.p256dh,auth=excluded.auth,username=excluded.username,updated_at=excluded.updated_at').bind(body.subscription.endpoint,body.subscription.keys.p256dh,body.subscription.keys.auth,user.username,Date.now()).run();return reply({ok:true})
}
