import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";
const code=fs.readFileSync(new URL("../../google-apps-script/Code.gs",import.meta.url),"utf8"),context={};vm.createContext(context);
vm.runInContext(code.match(/function constantEqual_[\s\S]*?\nfunction firmAccount_/)[0].replace(/\nfunction firmAccount_[\s\S]*/,""),context);
vm.runInContext(code.match(/function cell_[\s\S]*?\nfunction today_/)[0].replace(/\nfunction today_[\s\S]*/,""),context);
test("signature comparison rejects absent and incorrect signatures",()=>{assert.equal(context.constantEqual_("abcd","abcd"),true);assert.equal(context.constantEqual_("abcd","abce"),false);assert.equal(context.constantEqual_("abcd",undefined),false)});
test("sheet values that could become formulas are escaped",()=>{assert.equal(context.cell_("=IMPORTXML(\"x\")"),"'=IMPORTXML(\"x\")");assert.equal(context.cell_("Normal note"),"Normal note")});
test("save endpoint no longer exposes mail or scheduler actions",()=>{const route=fs.readFileSync(new URL("../app/api/workspace/route.ts",import.meta.url),"utf8");for(const action of ["prepareMorning","sendMorning","sendEvening","configureSchedule"])assert.equal(route.includes(action),false)});
